--- 
- 
  name: "terraform apply"
  register: apply_result
  terraform: 
    plan_file: "{{ projectDir }}/myplan.tfplan"
    project_path: "{{ projectDir }}"
    state: present
    variables: 
      ownerName: "{{ ownerName}}"      
      amiId: "{{ amiId }}"
      nameTag: "{{ nameTag }}"
      subnetId: "{{ subnetId }}"
- 
  debug: 
    var: apply_result.stdout_lines

